openapi: 3.0.0
info:
  title: Max Help API
  description: API documentation for Max Help project
  version: 1.0.0

servers:
  - url: "{{URL}}"
    description: Base URL for API

paths:
  /api/v1/products/products:
    post:
      summary: Add a product
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: czars
                price:
                  type: string
                  example: "56"
                stock:
                  type: string
                  example: "5"
                category:
                  type: string
                  example: david
      responses:
        "200":
          description: Product added successfully

  /api/v1/auth/signup:
    post:
      summary: Sign up a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: randomUserName
                email:
                  type: string
                  example: random@example.com
                password:
                  type: string
                  example: Kevin110@
      responses:
        "201":
          description: User signed up successfully

  /api/v1/auth/login:
    post:
      summary: Log in a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: dedrick.harris@yahoo.com
                password:
                  type: string
                  example: Kevin110@
      responses:
        "200":
          description: User logged in successfully

  /api/v1/catalogues:
    post:
      summary: Create a new catalogue
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Hweloe
                description:
                  type: string
                  example: Description for new catalog
                image:
                  type: string
                  format: binary
      responses:
        "201":
          description: Catalogue created successfully

  /api/v1/users:
    get:
      summary: Get all users
      security:
        - bearerAuth: []
      responses:
        "200":
          description: List of users returned

  /api/v1/users/{userId}:
    get:
      summary: Get a single user
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
          example: 6734bdc267997e5c3392f7bf
      responses:
        "200":
          description: User details returned

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
